version: "3.8"
services:
  zookeeper:
    image: zookeeper:3.7.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
  kafka:
      image: wurstmeister/kafka
      depends_on:
        - zookeeper
      ports:
        - "9092:9092"
      environment:
        KAFKA_ADVERTISED_HOST_NAME: kafka
        KAFKA_ADVERTISED_PORT: 9092
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  clientsdb:
    image: postgres:14
    container_name: clientsdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_RASSWORD=trypassword
      - POSTGRES_USER=Yulia_Zaitseva
      - POSTGRES_DB=clients
    restart: unless-stopped
  clients-service:
    image: clients-service
    build:
      context: ./clients-service
    container_name: clients-service
    expose:
      - 8080
    ports:
      - "8080:8080"
    depends_on:
      - clientsdb
      - orders-service
  drivers-service:
    image: drivers-service
    build:
      context: ./drivers-service
    container_name: drivers-service
    expose:
      - 8082
    ports:
      - "8082:8082"
    depends_on:
      - drivers-db
      - orders-service
      - order-history-service
  drivers-db:
    image: postgres
    environment:
      - POSTGRES_DB=drivers
    ports:
      - "5433:5432"
  orders-service:
    image: orders-service
    build:
      context: ./orders-service
    container_name: orders-service
    expose:
      - 8081
    ports:
      - "8081:8081"
    depends_on:
      - orders-db
      - kafka
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  orders-db:
    image: postgres
    environment:
      - POSTGRES_DB=orders
    ports:
      - "5435:5432"
  order-history-service:
    image: order-history-service
    build:
      context: ./order-history-service
    container_name: order-history-service
    expose:
      - 8083
    ports:
      - "8083:8083"
    depends_on:
      - order-history-db
      - kafka
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  order-history-db:
    image: postgres
    environment:
      - POSTGRES_DB=history
    ports:
      - "5434:5432"
volumes:
    postgres-data:

